Peyton Thomas
MIS 407
Java vs Javascript

	Over the recent years Java has started to turn into an industry standard. There are clear advantages to this programming language due to it's large array of libraries, it's object oriented structure, and it's ability to easily access and present data to the user. It has many business applications and there are even frameworks that make Java useful (to some extent) for web development. There are, however, limitations to the effectiveness of Java in specific applications. Things such as website development are better handled with a combination of html, css, and Javascript. Javascript offers element manipulation, a more readable functional style of programming, and increasingly useful frameworks and plugins for easy website development. For quite some time the two languages were seen as having clear strengths in their own respective applications. This changed, however with the growth of the mobile market.
	
	When a business decides they want to develop a mobile application one of the first decisions they have to make is whether they want to create something native to a specific phone OS or if they want to build a hybrid app that works on any major OS. This hybrid application is essentially a responsive web site that is wrapped in a container to appear as a mobile app. Therefore, hybrid applications are developed with Javascript. The obvious benefit for using this is the time savings. Having the ability to create one application that works on multiple phone operating systems is a huge time benefit but it comes at a cost; the loss of OS specific look and feel. Hybrid apps work well on different operating systems but they look more generic and often feel less natural than other applications. On the other hand, when creating a native android app one must develop it using Java. This naturally has the opposite set of problems. The android application will feel much smoother but the business will either have to take time to make the Iphone app, or they would simply not be able to reach Iphone users.
	
	Deciding whether to save time and money by going hybrid versus going with the native approach is challenging but there are some logical outcomes depending on what the company is doing. For example, if a business is not in a very technical industry or, if they are limited on IT resources they would probably create a hybrid application. On the other hand, if a company is in a tech driven industry it would be beneficial to spend the money on developing a Java app for Android to give the native feel. Unfortunately, this is not the only aspect to consider when making the decision. There are fundamental aspects of each programming language that make the difference much more complex.
	
	One way these languages are different is the way they are consumed by the user. Java is compiled on the server side and sent over, which takes up more bandwidth when sending. This is somewhat of a downside but there is also a major benefit; security. With the actual application code on the server side, it is much harder to view, leaving private information with the business rather than the customer. This naturally makes Java the better choice when there is sensitive business or customer data that needs protecting. On the other hand, if there is simply general data in the application files, then Javascript may be the best option. The benefit of Javascript being client side is that it is being processed on the user's machine, preventing data speeds from having as much of a factor on a business application.
	
	Both languages can be useful to all businesses, and in regards to mobile application development, there are useful cases for going with either option. With a company that is financially restricted, it generally makes more sense to develop an application with Javascript. While a company that is financial struggling may have no choice but to develop an application with Java due to the security benefits of this language. Ultimately, they both have a useful place in the business environment. The two options provide benefits in different ways to different companies but the correct decision will ultimately be dependent on a companies situation.
